apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
        - name: mlops-app
          image: mlops:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
